services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"     # MQTT broker port
      - "8083:8083"     # MQTT over WebSocket
      - "18083:18083"   # EMQX dashboard
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.io

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking
    volumes:
      - ./BackEnd/internal/db/migration/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - pgdata:/var/lib/postgresql

  app:
    build:
      context: ./BackEnd
      dockerfile: dockerfile
    image: ghcr.io/niflheimdevs/smartparking
    container_name: application
    restart: unless-stopped
    depends_on:
      - postgres
      - emqx
    ports:
      - "8080:8080"

volumes:
  pgdata:
